### ISSUE TITLE
font-size

### ISSUE THREAD

**Issue by iosbeis** [Schaffenburg/photobooth#4]
Hi,
it looks like all fonts are on default size.

font-size from css (80px for .countdown_label) is not used, but color changes are working

**Comment by fraxinas** [comment]
this is technically not a bug. you probably haven't defined a css in your ini configuration file. or haven't set an ini configuration file whatsoever. it only ships with a default-template.ini, but tries loading default.ini if no ini file is supplied as a command line argument. i did that because the ini also holds the localization but if this is confusing, i'll change the filename from default-template.ini to default.ini for the sample configuration to prevent confusion.
font-size 40
![screenshot_20170810_170239](https://user-images.githubusercontent.com/1109826/29177023-e42821a0-7ded-11e7-8c62-9a9a08d99100.png)
font-size 160
![screenshot_20170810_170314](https://user-images.githubusercontent.com/1109826/29177028-e6775124-7ded-11e7-8a19-ae523aaa0b87.png)
